### ISSUE TITLE
Зависание после ~5700 обновлений

### ISSUE THREAD

**Issue by legioner0** [alexshnup/sony_prs-505_remote_show#1]
После ~5700 обновлений читалка перестает реагировать — картинка не обновляется и отключение usb не приводит к выходу в tinyhttp. Помогает только ресет. Это проблемы с showpic или особенность прошивки?

**Comment by alexshnup** [comment]
Попробуйте проверять размер занятой оперативной памяти и найти утечку,
возможно требуется добавить очистку памяти после смены загрузки кадра.
Я думаю проблема в этом.

**Comment by legioner0** [comment]
Возможно память утекает в `prsp.sh` из-за рекурсивных вызовов `showpic` из `waitnewdata`, и `waitnewdata` из `showpic`. Поправил у себя. Отпишусь по результату.

**Comment by legioner0** [comment]
Замена на бесконечный цикл помогла - работает уже почти неделю без зависаний
